### PR TITLE
CMR-597 Replacing nbsp/bitter

### PR DESCRIPTION
**Pull request by chrizzor**
I've wrote a small test for the XPathXMLGenerator which is based on the nimut/TestingFramework.
However this tests needs further investigations if we defined our test framework for this extension.

Notice: The existing tests (Controller and Domain/Model) are throwing errors and they need to be removed or reimplemented.

### CODE REVIEW

**Comment by claussni** [comment]
The library is not removed from Classes/Services/parser with this PR. Is that on purpose? If so, why?

**Comment by chrizzor** [comment]
No purpose in this case. I simply missed it.

**Comment by claussni** [comment]
Thanks to #121 I managed to execute the code successfully. However, more intense mapping tests are required. Stay tuned...

**Comment by claussni** [comment]
Cannot set up complicated elements.
Cannot run unit tests.
See https://jira.slub-dresden.de/browse/CMR-597 (internal)

**Pull request merged**
