### PR TITLE
A new input field type with a dropdown box containing selectable valu…

### PR DESCRIPTION
**Pull request by haogatyp**
A new input field type with a dropdown box containing selectable value options. Alternatively, a value can also be entered directly.

### CODE REVIEW

**Comment by haogatyp** [comment]
A rebase was performed. 
From the Input-Option-List only the value list (list codes) is used.

**Comment by haogatyp** [comment]
Codacy issues havey been addressed.

**Comment by claussni** [comment]
**Fix required** 
I can use the field and enter text. But I cannot use the drop down. It's not showing a list.

**Modification possible?**
What is the reason it is only showing the list codes (values)? The fiels should show and work with the list labels for a user to understand and then write the codes to the form for further processing. Would it be an easy change to make it configurable thus that the form configuration has an option whether to show labels or list codes?

**Comment by claussni** [comment]
Branch works in Docker Environment. Something must be different with Java Script on production system.

**Pull request merged**
